"""Chat Fix

Revision ID: 0fabd4f633ba
Revises: b56de88d5222
Create Date: 2025-01-03 16:32:21.833877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fabd4f633ba'
down_revision = 'b56de88d5222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('mid')
        batch_op.drop_column('uid')
        batch_op.drop_column('ts')
        batch_op.drop_column('msg')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('msg', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('ts', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('uid', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('mid', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
