"""added temp users during email verification

Revision ID: 30c64475a35e
Revises: ad035fa38f05
Create Date: 2025-02-10 14:47:31.066800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c64475a35e'
down_revision = 'ad035fa38f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_users',
    sa.Column('pending_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('token_expiration', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pending_id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_constraint('email_verifications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('emergencies', schema=None) as batch_op:
        batch_op.drop_constraint('emergencies_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['assigned_employee_id'], ['user_id'])

    with op.batch_alter_table('mfa', schema=None) as batch_op:
        batch_op.drop_constraint('mfa_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mfa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('mfa_ibfk_1', 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('emergencies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('emergencies_ibfk_2', 'users', ['assigned_employee_id'], ['user_id'], onupdate='CASCADE', ondelete='SET NULL')

    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('email_verifications_ibfk_1', 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')

    op.drop_table('pending_users')
    # ### end Alembic commands ###
