"""2FA and account changes

Revision ID: 6844c6dc82b6
Revises: 0fabd4f633ba
Create Date: 2025-01-03 17:38:59.586927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6844c6dc82b6'
down_revision = '0fabd4f633ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mfa', schema=None) as batch_op:
        batch_op.drop_constraint('mfa_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mfa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('mfa_ibfk_1', 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
