"""Initial migration

Revision ID: b56de88d5222
Revises: 
Create Date: 2025-01-03 16:10:57.187654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b56de88d5222'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('ts')
        batch_op.drop_column('msg')
        batch_op.drop_column('uid')
        batch_op.drop_column('mid')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mid', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('uid', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('msg', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('ts', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
