"""added session tracking and emergency tags

Revision ID: ca6f2214226a
Revises: 
Create Date: 2025-01-13 13:30:28.537263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6f2214226a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergencies', schema=None) as batch_op:
        batch_op.drop_constraint('emergencies_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['assigned_employee_id'], ['user_id'])

    with op.batch_alter_table('mfa', schema=None) as batch_op:
        batch_op.drop_constraint('mfa_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mfa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('mfa_ibfk_1', 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('emergencies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('emergencies_ibfk_2', 'users', ['assigned_employee_id'], ['user_id'], onupdate='CASCADE', ondelete='SET NULL')

    # ### end Alembic commands ###
